"""create cassette_replies table

Revision ID: e96e478b6601
Revises: 041c3e7ca534
Create Date: 2026-03-10 22:08:21.469213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96e478b6601'
down_revision = '041c3e7ca534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cassette_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cassette_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=11), nullable=False),
    sa.Column('youtube_embed_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cassette_id'], ['cassettes.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cassette_replies_cassette_id'), 'cassette_replies', ['cassette_id'], unique=False)
    op.create_index(op.f('ix_cassette_replies_sender_id'), 'cassette_replies', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cassette_replies_sender_id'), table_name='cassette_replies')
    op.drop_index(op.f('ix_cassette_replies_cassette_id'), table_name='cassette_replies')
    op.drop_table('cassette_replies')
    # ### end Alembic commands ###
