"""add unique constraint to saved cassettes

Revision ID: 7abe8e73b240
Revises: 4ce2a1fbd01a
Create Date: 2026-03-10 03:27:19.642359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abe8e73b240'
down_revision = '4ce2a1fbd01a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_cassette', 'saved_cassettes', ['user_id', 'cassette_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_cassette', 'saved_cassettes', type_='unique')
    # ### end Alembic commands ###
