"""add saved cassette model

Revision ID: 041c3e7ca534
Revises: 7abe8e73b240
Create Date: 2026-03-10 04:47:57.010300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c3e7ca534'
down_revision = '7abe8e73b240'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_cassette', 'saved_cassettes', type_='unique')
    op.create_unique_constraint('uq_saved_cassettes_user_cassette', 'saved_cassettes', ['user_id', 'cassette_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_cassettes_user_cassette', 'saved_cassettes', type_='unique')
    op.create_unique_constraint('uq_user_cassette', 'saved_cassettes', ['user_id', 'cassette_id'])
    # ### end Alembic commands ###
