"""sync user auth changes

Revision ID: 4ce2a1fbd01a
Revises: 
Create Date: 2026-03-10 02:04:03.621668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce2a1fbd01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cassettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('share_code', sa.String(length=6), nullable=False),
    sa.Column('share_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=11), nullable=False),
    sa.Column('youtube_embed_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('letter_text', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('emotion_tag', sa.String(length=50), nullable=False),
    sa.Column('emotion_emoji', sa.String(length=10), nullable=False),
    sa.Column('sender_is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('unlock_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cassettes_sender_id'), 'cassettes', ['sender_id'], unique=False)
    op.create_index(op.f('ix_cassettes_share_code'), 'cassettes', ['share_code'], unique=True)
    op.create_table('saved_cassettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cassette_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cassette_id'], ['cassettes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_cassettes_cassette_id'), 'saved_cassettes', ['cassette_id'], unique=False)
    op.create_index(op.f('ix_saved_cassettes_user_id'), 'saved_cassettes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_cassettes_user_id'), table_name='saved_cassettes')
    op.drop_index(op.f('ix_saved_cassettes_cassette_id'), table_name='saved_cassettes')
    op.drop_table('saved_cassettes')
    op.drop_index(op.f('ix_cassettes_share_code'), table_name='cassettes')
    op.drop_index(op.f('ix_cassettes_sender_id'), table_name='cassettes')
    op.drop_table('cassettes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
